// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "xmodel/playerbody_american_normandy01";
	a[1] = "xmodel/playerbody_american_normandy05";
	a[2] = "xmodel/playerbody_american_normandy03";
	return a;
}
