// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "xmodel/head_british_boon";
	a[1] = "xmodel/head_british_paul";
	a[2] = "xmodel/head_british_chance";
	//a[3] = "xmodel/head_british_macgregor";
	return a;
}
