// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	if(isdefined(game["modeloverflow"]))
		character\mp_american_normandy_::main();
	else
		character\mp_american_normandy::main();
}

precache()
{
	if(isdefined(game["modeloverflow"]))
		character\mp_american_normandy_::precache();
	else
		character\mp_american_normandy::precache();
}
