// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	character\mp_german_winter::main();
}

precache()
{
	character\mp_german_winter::precache();
}
/*
main()
{

	switch(randomint(2))
	{
	case 0:
		character\mp_german_winterlight::main();
		break;
	case 1:
		character\mp_german_winterlight::main();
		break;
	//case 2:
	//	character\mp_german_winterdark_masked::main();
	//	break;
	}
}

precache()
{
	character\mp_german_winterdark::precache();
	//character\mp_german_winterdark_masked::precache();
	character\mp_german_winterlight::precache();
}
