// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "xmodel/head_us_ranger_david";
	a[1] = "xmodel/head_us_ranger_wolf";
	a[2] = "xmodel/head_us_ranger_braeburn";
	a[3] = "xmodel/head_us_ranger_harry";
	return a;
}
